### ISSUE TITLE
All configured authentication methods failed

### ISSUE THREAD

**Issue by xiaooojun** [ChiChou/fruity-frida#4]
iPhone6s 帕梅拉越狱 15.7.5 命令iOS-shell

**Comment by ChiChou** [comment]
如果你改过 SSH 密码，需要加环境变量
https://github.com/ChiChou/fruity-frida/blob/25e4ece40e5f/modules/ssh.ts#L42

**Comment by xiaooojun** [comment]
我明白问题所在了，，我采取的越狱环境 不能通过root账户登录。。。

**Comment by xiaooojun** [comment]
我配置下环境变量

**Comment by xiaooojun** [comment]
signed /Developer/usr/bin/debugserver debugserver to /var/root/debugserver
remote free port 1024
attach to attach
remote >> /var/root/debugserver 127.1:1024 -a 'attach'
remote >> %                                                                               
remote >>  
remote >> 
remote >> iPhone6s:~ mobile% /var/root/debugserver 127.1:1024 -a 'attach'
remote >> 
remote >> zsh: killed     /var/root/debugserver 127.1:1024 -a 'attach'
remote >> %                                                                               
remote >>  
remote >> 


这个lldb工具 是正常的吗 敲了没反应。。。

**Comment by xiaooojun** [comment]
[~] ios-debug app com.apple.findmy                                                                            11:20:45
signed /Developer/usr/bin/debugserver debugserver to /var/root/debugserver
remote free port 1024
attach to app
remote >> /var/root/debugserver 127.1:1024 -a 'app'
remote >> %
remote >>
remote >>
remote >> iPhone6s:~ mobile% /var/root/debugserver 127.1:1024 -a 'app'
remote >>
remote >> zsh: killed     /var/root/debugserver 127.1:1024 -a 'app'
remote >> %
remote >>
remote >>

大佬。。这个功能没搞懂咋用。。

**Comment by xiaooojun** [comment]
[~] ios-debug app com.apple.findmy                                                                            11:20:45
signed /Developer/usr/bin/debugserver debugserver to /var/root/debugserver
remote free port 1024
attach to app
remote >> /var/root/debugserver 127.1:1024 -a 'app'
remote >> %
remote >>
remote >>
remote >> iPhone6s:~ mobile% /var/root/debugserver 127.1:1024 -a 'app'
remote >>
remote >> zsh: killed     /var/root/debugserver 127.1:1024 -a 'app'
remote >> %
remote >>
remote >>

大佬 这个功能没搞懂咋用

**Comment by xiaooojun** [comment]
> 我配置下环境变量

这个我看了下，最新的源码

> 如果你改过 SSH 密码，需要加环境变量 https://github.com/ChiChou/fruity-frida/blob/25e4ece40e5f/modules/ssh.ts#L42

这个问题，我看了下最新地源码 好像上面的逻辑，不过我把默认值改了下，完美登录

**Comment by xiaooojun** [comment]
> [~] ios-debug app com.apple.findmy 11:20:45 signed /Developer/usr/bin/debugserver debugserver to /var/root/debugserver remote free port 1024 attach to app remote >> /var/root/debugserver 127.1:1024 -a 'app' remote >> % remote >> remote >> remote >> iPhone6s:~ mobile% /var/root/debugserver 127.1:1024 -a 'app' remote >> remote >> zsh: killed /var/root/debugserver 127.1:1024 -a 'app' remote >> % remote >> remote >>
> 
> 大佬 这个功能没搞懂咋用

看了下源码测试了下，是因为下面这个函数 获取不到对应的参数值
let target = program.getOptionValue('app');

**Comment by xiaooojun** [comment]
[shellArgs.push('attach', node.data.pid.toString());](https://github.com/ChiChou/vscode-frida/blob/2819adc34a6584e33435cc34abdabb36642f44bd/src/commands/lldb.ts#L29C3-L29C3)
这里是不是少一个 - 导致参数获取不到

**Comment by ChiChou** [comment]
> [shellArgs.push('attach', node.data.pid.toString());](https://github.com/ChiChou/vscode-frida/blob/2819adc34a6584e33435cc34abdabb36642f44bd/src/commands/lldb.ts#L29C3-L29C3) 这里是不是少一个 - 导致参数获取不到

已修复和发布新版
