### ISSUE TITLE
node最新版本问题

### ISSUE THREAD

**Issue by L0veHeather** [ChiChou/fruity-frida#5]
版本：iOS15.1
          node@20
报错：
npm ERR! code 1
npm ERR! path /opt/homebrew/lib/node_modules/fruity-frida/node_modules/frida
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install No prebuilt binaries found (target=20.5.1 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.5.1 | darwin | arm64

运行命令会报错：
ios-shell:
/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/bindings@1.5.0/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/Debug/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/Release/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/out/Debug/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/Debug/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/out/Release/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/Release/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/default/frida_binding.node
 → /opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/compiled/20.5.1/darwin/arm64/frida_binding.node
 → /Users/melrose/frida_binding.node
    at bindings (/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/bindings@1.5.0/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/dist/native.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/dist/cancellable.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1233:14) {
  tries: [
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/Debug/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/Release/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/out/Debug/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/Debug/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/out/Release/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/Release/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/build/default/frida_binding.node',
    '/opt/homebrew/lib/node_modules/fruity-frida/node_modules/.store/frida@16.1.3/node_modules/frida/compiled/20.5.1/darwin/arm64/frida_binding.node',
    '/Users/melrose/frida_binding.node'
  ]
}

Node.js v20.5.1

**Comment by ChiChou** [comment]
文档已经写了要用 lts

**Comment by L0veHeather** [comment]
还是一样的报错，翻墙代理、npm配置全都修改过了。
melrose@shuaige ~ % nvm install --lts
Installing latest LTS version.
v18.17.1 is already installed.
Now using node v18.17.1 (npm v9.6.7)
melrose@shuaige ~ % nvm use --lts
Now using node v18.17.1 (npm v9.6.7)
melrose@shuaige ~ % npm install -g fruity-frida
npm ERR! code 1
npm ERR! path /Users/melrose/.nvm/versions/node/v18.17.1/lib/node_modules/fruity-frida/node_modules/frida
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install aborted
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.17.1 | darwin | arm64

主要是这个报错：Command failed with exit code 1: prebuild-install || node-gyp rebuild

**Comment by ChiChou** [comment]
**node@18.17.1 绝对不会出现这个问题。**

加上 -v 会打印详细的错误日志：`npm install -g fruity-frida -v`

推测可能的原因：

1. 你的代理配置没有导出到 https_proxy/http_proxy
2. 你的代理规则没有覆盖到 frida 官方二进制包的域名

后面不再针对这个帖子回复了……

**Comment by cfossace** [comment]
These versions worked for me:

➜  npm --version                                                    
9.8.1
➜  node --version
v18.18.2
